### ISSUE TITLE
Importing standard library packages manually causes them to be imported twice.

### ISSUE THREAD

**Issue by dmitshur** [sriram-srinivasan/gore#4]
If you want to use an external library, you'd have to do import it manually:

``` bash
$ gore 'import "github.com/davecgh/go-spew/spew"
spew.Dump("this works fine")'
--------------------
(string) "this works fine"
```

But if you import "fmt" or any other standard library, like this:

``` bash
$ gore 'import "github.com/davecgh/go-spew/spew"
import "fmt"
spew.Dump(fmt.Sprint("this will fail to compile"))'
===== Error =====
:2: fmt redeclared as imported package name
    previous declaration at /tmp/gore_eval.go:3
```

The generated gore_eval.go ends up being:

``` Go
package main
import "fmt"

//line :1
import "github.com/davecgh/go-spew/spew"
//line :2
import "fmt"

func main() {
...
```

I understand that it's not necessary to import standard library packages because they can be automatically inferred, but still. This shouldn't result in an error.

> Of course, you can add import statements of your own (which overrides the default preferences as well)

Exactly. It shouldn't cause errors.

**Comment by sriram-srinivasan** [comment]
> But if you import "fmt" or any other standard library, like this:
> 
> $ gore 'import "github.com/davecgh/go-spew/spew"
> import "fmt"
> spew.Dump(fmt.Sprint("this will fail to compile"))'
> ===== Error =====

You are right. It should not cause an error. It is a bug. I'll look into it.

**Comment by sriram-srinivasan** [comment]
Fixed.

**Comment by dmitshur** [comment]
Oh, so this was only affecting the "fmt" package and not all standard packages like I assumed. Anyway, it's great to have it fixed now, thanks! :+1:

**Comment by sriram-srinivasan** [comment]
On May 2, 2013, at 10:03 PM, Dmitri Shuralyov wrote:

> Oh, so this was only affecting the "fmt" package and not all standard packages like I assumed. Anyway, it's great to have it fixed now, thanks! 

You are welcome. Yes, it was a really stupid bug! I tested it with other packages, not with "fmt"!

**Comment by dmitshur** [comment]
By the way, in the [bugs](https://github.com/sriram-srinivasan/gore#bugs) section it says,

> `gore` doesn't correctly handle trailing '{' and '(' inside backtick-quotes.

Is the problem within `gore` or `gore/eval`? Can you give an example that fails? I'd like to take a shot at fixing it. :)

**Comment by sriram-srinivasan** [comment]
On May 2, 2013, at 10:08 PM, Dmitri Shuralyov wrote:

> By the way, in the bugs section it says,
> 
> gore doesn't correctly handle trailing '{' and '(' inside backtick-quotes.
> 
> Is the problem within gore or gore/eval? Can you give an example that fails? I'd like to give it a shot to fix it. :)

gore '
fmt.Printf(`hello {
world`)
'

Notice the '{'  after hello that does not have a corresponding '}'.   I look for '{' and assume they are outside strings. The correct way to do it would be to ignore brackets and curlies inside comments and strings. 

The other problem with using backticks is that I insert line numbers of the form //line :n , so that if there is a compiler error, the go compiler points to the offending line. But if one uses backticks over multiple lines, these embedded line numbers form part of the printout. They should be filtered out of the output.
