### ISSUE TITLE
How to exit gore?

### ISSUE THREAD

**Issue by stanim** [sriram-srinivasan/gore#9]
No idea if this is a missing or hidden feature. In stdin mode, it is not clear how to exit gore. It could be something like:

```
:exit
:quit
```

It would also be good to mention it on the README.

**Comment by theclapp** [comment]
The current code prints "Enter one or more lines **and hit ctrl-D**".  Was that not clear?

**Comment by stanim** [comment]
Sorry, filed to the wrong repository. My mistake
